---
spring:
  redis:
    host: localhost
    port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 60000
  output:
    ansi:
      enabled: ALWAYS

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      show-details: never
      cache:
        time-to-live: 20000ms
    info:
      enabled: true

server:
  port: 9100
  error:
    include-message: always

info:
  build:
    group: @project.groupId@
    artifact: @project.artifactId@
    version: @project.version@
    name: @project.name@

inventory:
  active-items:
    enabled: true
    cron-period: 0 * * * * *
---
spring.profiles: cosmos

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration, org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
  data:
    mongodb:
      database: mdt
      host: localhost
      user: root
      password: root
      port: 27017
      appName: mdt
      isSsl: false
      withSha1: false
---
