---
spring:
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    database: ${REDIS_DATABASE:0}
    timeToLive: ${REDIS_EXPIRE_TIME:2592000}
  cache:
    type: redis
    redis:
      time-to-live: 60000
  jackson:
    serialization:
      INDENT_OUTPUT: false
      WRITE_DATES_AS_TIMESTAMPS: false
    default-property-inclusion: NON_NULL
  output:
    ansi:
      enabled: ALWAYS

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      show-details: never
      cache:
        time-to-live: 20000ms
    info:
      enabled: true

server:
  compression:
    enabled: true
  port: ${SERVER_PORT:9100}
  error:
    include-message: always

info:
  build:
    group: @project.groupId@
    artifact: @project.artifactId@
    version: @project.version@
    name: Reference

inventory:
  active-items:
    enabled: true
    cron-period: 0 * * * * *

azure:
  serviceBus:
    connectionString: ${SERVICE_BUS_ENDPOINT:Endpoint=sb://tech.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=P8UtCBChC+d6UoxaIXjiNeMt6Vr8f658746QdUH5ABg=}
    topicName: ${TOPIC_NAME:mdt_price}
    subscriptionName: ${SUBSCRIPTION_NAME:mdt_api}

---
spring.profiles: mysql

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_SCHEMA:hexa}?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${MYSQ_USER:root}
    password: ${MYSQ_PASSWORD:root}
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.hbm2ddl.import_files: schema.sql
---
spring.profiles: h2

spring:
  datasource:
    url: jdbc:h2:file:~/data/demoRefKt;TRACE_LEVEL_FILE=4
    driverClassName: org.h2.Driver
    username: sa
    password: password
    initialization-mode: never
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate.hbm2ddl.import_files: schema.sql
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: true
        web-allow-others: true
---