spring:
  datasource:
#    url: jdbc:h2:file:~/data/demoRef;TRACE_LEVEL_FILE=4
#    driverClassName: org.h2.Driver
#    username: sa
#    password: password
    url: jdbc:mysql://localhost:3306/hexa?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
#    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
#      ddl-auto: update
       ddl-auto: update
  output:
    ansi:
      enabled: ALWAYS
  h2:
    console:
      enabled: false
      path: /h2-console
      settings:
        trace: false
        web-allow-others: true
  redis:
    host: localhost
    port: 6379

  cache:
    type: redis
    redis:
      time-to-live: 60000

inventory:
  active-items:
    enabled: true
    cron-period: 0 * * * * *

server:
  port: 9100

