DROP TABLE if exists book_data;


CREATE TABLE IF NOT EXISTS shedlock(name VARCHAR(64) NOT NULL, lock_until TIMESTAMP(3) NOT NULL, locked_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), locked_by VARCHAR(255) NOT NULL, PRIMARY KEY (name));

CREATE TABLE IF NOT EXISTS  book_data(id BIGINT generated by default as identity,  author varchar(255),  available boolean,  isbn bigint,  name varchar(255),  properties varchar(255),  quantity integer,  start_sale_date timestamp,  status varchar(255),  PRIMARY KEY (id));

CREATE TABLE IF NOT EXISTS publishing_house_data(id BIGINT generated by default as identity, name varchar(255), address varchar(255), is_active boolean, PRIMARY KEY (id));